// ╔══════════════════════════════════════════════════════════════╗
// ║  DONNÉES MENUS — mis à jour chaque mardi par cowork          ║
// ║  Ne modifier que semaine1 et semaine2                        ║
// ╚══════════════════════════════════════════════════════════════╝

// ── DONNÉES SEMAINE 1 ──────────────────────────────────────────
const semaine1=[
  {f:[
    {moment:'Petit-déjeuner',nom:'Skyr banane flocons noisettes',kcal:380,p:22,g:50,l:10,portions:'2 adultes',ings:['Skyr 150g','Flocons avoine 45g','Banane 60g','Noisettes 12g'],steps:['Verser le skyr dans un bol.','Trancher la banane et l\'ajouter.','Parsemer flocons et noisettes.','Déguster frais.'],note:''},
    {moment:'Déjeuner',nom:'Maquereau fumé riz basmati épinards',kcal:450,p:26,g:44,l:18,portions:'2 adultes',ings:['Maquereau fumé en boîte 80g','Riz basmati 65g','Épinards frais 80g','Ail','Huile olive 4g','Citron herbes'],steps:['Cuire le riz basmati 12 min.','Faire sauter les épinards avec l\'ail 3 min.','Émietter le maquereau fumé.','Servir riz + épinards + maquereau avec citron pressé.'],note:'Poisson gras riche en oméga-3.'},
    {moment:'Collation',nom:'Yaourt fruits mixé beurre cacahuète',kcal:200,p:8,g:18,l:10,portions:'2 adultes',ings:['Yaourt fruits mixé 150g','Beurre cacahuète 10g'],steps:['Mélanger le beurre de cacahuète dans le yaourt.','Déguster.'],note:''},
    {moment:'Dîner',nom:'Curry pois chiches épinards patate douce',kcal:400,p:18,g:54,l:12,portions:'4 pers.',ings:['Pois chiches en bocal 70g','Patate douce 80g','Épinards frais 60g','Lait de coco 25ml','Oignon','Ail','Curry doux','Huile olive 2g'],steps:['Faire revenir oignon + ail + curry dans l\'huile 2 min.','Ajouter patate douce en dés + 200ml d\'eau, cuire 10 min.','Ajouter pois chiches + lait de coco, chauffer 3 min.','Incorporer les épinards 2 min.','Servir chaud.'],note:'Plat végétarien 18 min. Doux et parfumé pour les enfants.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Skyr banane flocons noisettes',kcal:440,p:27,g:60,l:12,portions:'2 adultes',ings:['Skyr 180g','Flocons avoine 60g','Banane 80g','Noisettes 15g','Miel 5g'],steps:['Verser le skyr dans un bol.','Trancher la banane et l\'ajouter.','Parsemer flocons et noisettes.','Ajouter un filet de miel.'],note:''},
    {moment:'Déjeuner',nom:'Maquereau fumé riz basmati épinards',kcal:515,p:32,g:52,l:20,portions:'2 adultes',ings:['Maquereau fumé en boîte 100g','Riz basmati 80g','Épinards frais 80g','Ail','Huile olive 5g','Citron herbes'],steps:['Cuire le riz basmati 12 min.','Faire sauter les épinards avec l\'ail 3 min.','Émietter le maquereau fumé.','Servir avec citron pressé.'],note:'Poisson gras riche en oméga-3.'},
    {moment:'Collation',nom:'Yaourt fruits mixé beurre cacahuète',kcal:215,p:10,g:18,l:12,portions:'2 adultes',ings:['Yaourt fruits mixé 150g','Beurre cacahuète 15g'],steps:['Mélanger le beurre de cacahuète dans le yaourt.','Déguster.'],note:''},
    {moment:'Dîner',nom:'Curry pois chiches épinards patate douce',kcal:400,p:18,g:54,l:12,portions:'4 pers.',ings:['Pois chiches en bocal 70g','Patate douce 80g','Épinards frais 60g','Lait de coco 25ml','Oignon','Ail','Curry doux','Huile olive 2g'],steps:['Faire revenir oignon + ail + curry dans l\'huile 2 min.','Ajouter patate douce en dés + eau, cuire 10 min.','Ajouter pois chiches + lait de coco, chauffer 3 min.','Incorporer les épinards 2 min.','Servir chaud.'],note:'Plat végétarien 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine poire noix cannelle',kcal:340,p:12,g:52,l:10,portions:'2 adultes',ings:['Flocons avoine 55g','Lait végétal 100ml','Poire 80g','Noix 12g','Cannelle'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Couper la poire en dés et l\'incorporer.','Parsemer noix et cannelle.','Servir chaud.'],note:''},
    {moment:'Déjeuner',nom:'Blanc poulet riz basmati poivrons sauce moutarde',kcal:455,p:38,g:44,l:12,portions:'2 adultes',ings:['Blanc poulet 100g','Riz basmati 65g','Poivron rouge 100g','Moutarde 10g','Huile olive 4g','Ail herbes'],steps:['Cuire le riz basmati 12 min.','Poêler le poivron en lamelles 5 min.','Poêler le poulet en lanières 7 min, badigeonner de moutarde à mi-cuisson.','Servir riz + poulet + poivrons.'],note:''},
    {moment:'Collation',nom:'Skyr amandes',kcal:175,p:13,g:9,l:10,portions:'2 adultes',ings:['Skyr 150g','Amandes 15g'],steps:['Déguster ensemble.'],note:''},
    {moment:'Dîner',nom:'Omelette courgettes tomates herbes',kcal:300,p:18,g:12,l:20,portions:'4 pers.',ings:['Oeufs 2 pièces','Courgette 100g','Tomates 80g','Ail','Huile olive 4g','Herbes de Provence'],steps:['Faire revenir courgette en rondelles + ail 4 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs et verser sur les légumes.','Cuire à feu doux 5 min, finir sous le gril 2 min.','Parsemer d\'herbes fraîches et servir.'],note:'Repas léger rapide 15 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:148,p:4,g:9,l:11,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge avoine poire noix cannelle',kcal:395,p:15,g:62,l:12,portions:'2 adultes',ings:['Flocons avoine 70g','Lait végétal 120ml','Poire 100g','Noix 15g','Cannelle'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Couper la poire en dés et l\'incorporer.','Parsemer noix et cannelle.','Servir chaud.'],note:''},
    {moment:'Déjeuner',nom:'Blanc poulet riz basmati poivrons sauce moutarde',kcal:515,p:46,g:50,l:14,portions:'2 adultes',ings:['Blanc poulet 130g','Riz basmati 80g','Poivron rouge 100g','Moutarde 12g','Huile olive 5g','Ail herbes'],steps:['Cuire le riz basmati 12 min.','Poêler le poivron en lamelles 5 min.','Poêler le poulet 7 min, badigeonner de moutarde.','Servir riz + poulet + poivrons.'],note:''},
    {moment:'Collation',nom:'Skyr amandes',kcal:200,p:16,g:10,l:11,portions:'2 adultes',ings:['Skyr 170g','Amandes 18g'],steps:['Déguster ensemble.'],note:''},
    {moment:'Dîner',nom:'Omelette courgettes tomates herbes',kcal:350,p:21,g:14,l:24,portions:'4 pers.',ings:['Oeufs 3 pièces','Courgette 100g','Tomates 80g','Ail','Huile olive 4g','Herbes de Provence'],steps:['Faire revenir courgette + ail 4 min.','Ajouter les tomates en dés, cuire 2 min.','Battre les oeufs et verser.','Cuire 5 min, finir sous le gril 2 min.','Parsemer d\'herbes fraîches.'],note:'Repas léger rapide 15 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:140,p:4,g:8,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr fraises flocons amandes',kcal:335,p:20,g:38,l:11,portions:'2 adultes',ings:['Skyr 150g','Fraises 100g','Flocons avoine 40g','Amandes 12g'],steps:['Verser le skyr dans un bol.','Couper les fraises en deux.','Parsemer flocons et amandes.','Servir frais.'],note:''},
    {moment:'Déjeuner',nom:'Boeuf haché poêlée courgettes poivrons riz basmati',kcal:460,p:35,g:44,l:14,portions:'2 adultes',ings:['Boeuf haché maigre 100g','Riz basmati 65g','Courgette 80g','Poivron rouge 80g','Oignon','Ail','Huile olive 4g','Herbes de Provence'],steps:['Cuire le riz basmati 12 min.','Faire revenir oignon + ail 2 min.','Ajouter courgette + poivron en dés, cuire 5 min.','Ajouter le boeuf haché, dorer 6 min en remuant.','Assaisonner aux herbes, servir avec le riz.'],note:''},
    {moment:'Collation',nom:'Petit suisse miel noix',kcal:165,p:6,g:14,l:9,portions:'2 adultes',ings:['Petit suisse 100g','Miel 8g','Noix 10g'],steps:['Verser le miel sur le petit suisse.','Parsemer les noix.'],note:''},
    {moment:'Dîner',nom:'Soupe minestrone légumes pois chiches',kcal:350,p:14,g:52,l:8,portions:'4 pers.',ings:['Pois chiches en bocal 60g','Carottes 50g','Courgette 50g','Tomates concassées 75g','Pâtes complètes 25g','Oignon','Ail','Bouillon légumes 200ml','Basilic','Huile olive 2g'],steps:['Faire revenir oignon + ail + carottes 4 min.','Ajouter courgette + tomates concassées + bouillon + pois chiches.','Porter à ébullition, ajouter les pâtes complètes.','Cuire 8 min.','Parsemer de basilic frais et servir.'],note:'Soupe-repas végétarienne 18 min. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr fraises flocons amandes',kcal:390,p:25,g:46,l:12,portions:'2 adultes',ings:['Skyr 180g','Fraises 100g','Flocons avoine 55g','Amandes 15g'],steps:['Verser le skyr dans un bol.','Couper les fraises en deux.','Parsemer flocons et amandes.','Servir frais.'],note:''},
    {moment:'Déjeuner',nom:'Boeuf haché poêlée courgettes poivrons riz basmati',kcal:525,p:42,g:52,l:16,portions:'2 adultes',ings:['Boeuf haché maigre 130g','Riz basmati 80g','Courgette 80g','Poivron rouge 80g','Oignon','Ail','Huile olive 5g','Herbes de Provence'],steps:['Cuire le riz basmati 12 min.','Faire revenir oignon + ail 2 min.','Ajouter courgette + poivron, cuire 5 min.','Ajouter le boeuf haché, dorer 6 min.','Assaisonner aux herbes, servir avec le riz.'],note:''},
    {moment:'Collation',nom:'Petit suisse miel noix',kcal:200,p:8,g:17,l:12,portions:'2 adultes',ings:['Petit suisse 100g','Miel 10g','Noix 14g'],steps:['Verser le miel sur le petit suisse.','Parsemer les noix.'],note:''},
    {moment:'Dîner',nom:'Soupe minestrone légumes pois chiches',kcal:350,p:14,g:52,l:8,portions:'4 pers.',ings:['Pois chiches en bocal 60g','Carottes 50g','Courgette 50g','Tomates concassées 75g','Pâtes complètes 25g','Oignon','Ail','Bouillon légumes 200ml','Basilic','Huile olive 2g'],steps:['Faire revenir oignon + ail + carottes 4 min.','Ajouter courgette + tomates + bouillon + pois chiches.','Porter à ébullition, ajouter les pâtes.','Cuire 8 min.','Parsemer basilic frais.'],note:'Soupe-repas végétarienne 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Oeufs brouillés pain complet tomates',kcal:335,p:22,g:26,l:16,portions:'2 adultes',ings:['Oeufs 2 pièces','Pain complet 40g','Tomates 100g','Huile olive 4g','Ciboulette'],steps:['Battre les oeufs et cuire à feu doux en remuant 4 min.','Toaster le pain complet.','Couper les tomates en tranches.','Servir oeufs brouillés + pain + tomates avec ciboulette.'],note:''},
    {moment:'Déjeuner',nom:'Thon riz complet tomates cerises avocat',kcal:450,p:34,g:44,l:16,portions:'2 adultes',ings:['Thon en boîte 120g','Riz complet 65g','Tomates cerises 80g','Avocat 50g','Huile olive 4g','Citron herbes'],steps:['Cuire le riz complet 18 min.','Égoutter le thon.','Couper l\'avocat en dés et les tomates cerises en deux.','Assembler riz + thon + avocat + tomates cerises.','Assaisonner huile + citron + herbes.'],note:'Préparer le riz la veille pour gagner du temps.'},
    {moment:'Collation',nom:'Yaourt fruits mixé amandes',kcal:172,p:7,g:18,l:8,portions:'2 adultes',ings:['Yaourt fruits mixé 130g','Amandes 13g'],steps:['Déguster ensemble.'],note:''},
    {moment:'Dîner',nom:'Galettes courgettes pois chiches oeufs',kcal:400,p:20,g:44,l:16,portions:'4 pers.',ings:['Pois chiches en bocal 70g','Courgette 100g','Oeufs 1 pièce','Oignon','Farine complète 12g','Cumin coriandre','Huile olive 4g'],steps:['Mixer pois chiches + oeuf + farine + épices.','Râper la courgette, presser pour enlever l\'eau, incorporer.','Façonner des galettes.','Cuire 4 min/face dans l\'huile.','Servir avec une salade verte.'],note:'Galettes végétariennes rapides 18 min. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Oeufs brouillés pain complet tomates',kcal:395,p:27,g:32,l:18,portions:'2 adultes',ings:['Oeufs 3 pièces','Pain complet 50g','Tomates 100g','Huile olive 5g','Ciboulette'],steps:['Battre les oeufs et cuire à feu doux en remuant 4 min.','Toaster le pain complet.','Couper les tomates.','Servir avec ciboulette.'],note:''},
    {moment:'Déjeuner',nom:'Thon riz complet tomates cerises avocat',kcal:515,p:40,g:52,l:18,portions:'2 adultes',ings:['Thon en boîte 150g','Riz complet 80g','Tomates cerises 80g','Avocat 60g','Huile olive 5g','Citron herbes'],steps:['Cuire le riz complet 18 min.','Égoutter le thon.','Couper l\'avocat et les tomates cerises.','Assembler et assaisonner.'],note:'Préparer le riz la veille pour gagner du temps.'},
    {moment:'Collation',nom:'Yaourt fruits mixé amandes',kcal:200,p:9,g:20,l:10,portions:'2 adultes',ings:['Yaourt fruits mixé 170g','Amandes 15g'],steps:['Déguster ensemble.'],note:''},
    {moment:'Dîner',nom:'Galettes courgettes pois chiches oeufs',kcal:400,p:20,g:44,l:16,portions:'4 pers.',ings:['Pois chiches en bocal 70g','Courgette 100g','Oeufs 1 pièce','Oignon','Farine complète 12g','Cumin coriandre','Huile olive 4g'],steps:['Mixer pois chiches + oeuf + farine + épices.','Râper la courgette, presser pour enlever l\'eau, incorporer.','Façonner des galettes.','Cuire 4 min/face dans l\'huile.','Servir avec salade verte.'],note:'Galettes végétariennes rapides 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine kiwi amandes',kcal:335,p:14,g:48,l:10,portions:'2 adultes',ings:['Flocons avoine 55g','Skyr 80g','Lait végétal 50ml','Kiwi 80g','Amandes 12g','Cannelle'],steps:['Mélanger flocons + skyr + lait végétal la veille au soir.','Le matin : couper le kiwi et l\'ajouter.','Parsemer amandes et cannelle.','Déguster froid.'],note:''},
    {moment:'Déjeuner',nom:'Blanc poulet pâtes complètes courgettes basilic',kcal:450,p:36,g:44,l:12,portions:'2 adultes',ings:['Blanc poulet 100g','Pâtes complètes 65g','Courgette 100g','Ail','Basilic','Huile olive 4g','Citron'],steps:['Cuire les pâtes complètes 8-10 min.','Poêler le poulet en lanières 7 min.','Faire sauter la courgette en rondelles 4 min.','Mélanger pâtes + poulet + courgette + citron + basilic.','Servir immédiatement.'],note:''},
    {moment:'Collation',nom:'Skyr beurre cacahuète',kcal:177,p:13,g:9,l:9,portions:'2 adultes',ings:['Skyr 150g','Beurre cacahuète 12g'],steps:['Mélanger ou déguster séparément.'],note:''},
    {moment:'Dîner',nom:'Soupe lentilles corail carottes cumin',kcal:360,p:18,g:52,l:8,portions:'4 pers.',ings:['Lentilles corail 60g','Carottes 80g','Oignon','Ail','Bouillon légumes 300ml','Cumin','Huile olive 2g','Persil'],steps:['Faire revenir oignon + ail + cumin dans l\'huile 2 min.','Ajouter carottes en rondelles + lentilles corail + bouillon.','Cuire 12 min à feu moyen.','Mixer légèrement et assaisonner.','Parsemer de persil frais.'],note:'Soupe consistante et rapide 15 min. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:148,p:4,g:9,l:11,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bircher avoine kiwi amandes',kcal:390,p:18,g:56,l:12,portions:'2 adultes',ings:['Flocons avoine 70g','Skyr 100g','Lait végétal 60ml','Kiwi 100g','Amandes 15g','Cannelle'],steps:['Mélanger flocons + skyr + lait végétal la veille.','Le matin : couper le kiwi et l\'ajouter.','Parsemer amandes et cannelle.','Déguster froid.'],note:''},
    {moment:'Déjeuner',nom:'Blanc poulet pâtes complètes courgettes basilic',kcal:515,p:44,g:52,l:14,portions:'2 adultes',ings:['Blanc poulet 130g','Pâtes complètes 80g','Courgette 100g','Ail','Basilic','Huile olive 5g','Citron'],steps:['Cuire les pâtes complètes 8-10 min.','Poêler le poulet en lanières 7 min.','Faire sauter la courgette 4 min.','Mélanger et assaisonner basilic + citron.'],note:''},
    {moment:'Collation',nom:'Skyr beurre cacahuète',kcal:177,p:13,g:9,l:9,portions:'2 adultes',ings:['Skyr 150g','Beurre cacahuète 12g'],steps:['Mélanger ou déguster séparément.'],note:''},
    {moment:'Dîner',nom:'Soupe lentilles corail carottes cumin',kcal:360,p:18,g:52,l:8,portions:'4 pers.',ings:['Lentilles corail 60g','Carottes 80g','Oignon','Ail','Bouillon légumes 300ml','Cumin','Huile olive 2g','Persil'],steps:['Faire revenir oignon + ail + cumin 2 min.','Ajouter carottes + lentilles corail + bouillon.','Cuire 12 min.','Mixer légèrement.','Parsemer de persil frais.'],note:'Soupe consistante et rapide 15 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:140,p:4,g:8,l:10,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine framboises skyr famille',kcal:355,p:18,g:50,l:11,portions:'4 pers.',ings:['Flocons avoine mixés 30g','Oeufs 1 pièce','Lait végétal 30ml','Skyr 30g','Framboises 50g','Miel 4g'],steps:['Mixer flocons + oeufs + lait en pâte lisse.','Cuire des pancakes 3 min/face à feu moyen.','Servir avec skyr, framboises et miel.'],note:'Les enfants adorent !'},
    {moment:'Déjeuner',nom:'Cuisses poulet rôties légumes du four patate douce',kcal:475,p:38,g:40,l:18,portions:'4 pers.',ings:['Cuisses poulet désossées 100g','Patate douce 120g','Courgette 60g','Poivron rouge 60g','Oignon','Ail','Huile olive 4g','Herbes de Provence'],steps:['Préchauffer le four à 200°C.','Couper les légumes, disposer dans un plat avec huile + herbes.','Déposer les cuisses de poulet par-dessus.','Rôtir 30 min en retournant à mi-cuisson.','Servir directement depuis le plat.'],note:'Plat du week-end (35 min). Simple et savoureux.'},
    {moment:'Collation',nom:'Yaourt fruits mixé noisettes famille',kcal:155,p:5,g:20,l:7,portions:'4 pers.',ings:['Yaourt fruits mixé 150g','Noisettes 10g'],steps:['Répartir en bols.','Parsemer les noisettes.'],note:''},
    {moment:'Dîner',nom:'Bolognaise pois chiches carottes pâtes complètes',kcal:440,p:20,g:60,l:12,portions:'4 pers.',ings:['Pois chiches en bocal 70g','Carottes 40g','Tomates concassées 80g','Oignon','Ail','Pâtes complètes 70g','Huile olive 3g','Herbes de Provence'],steps:['Faire revenir oignon + ail + carottes en dés 5 min.','Ajouter pois chiches + tomates concassées + 100ml d\'eau + herbes.','Mijoter 15 min à feu doux.','Cuire les pâtes complètes 8-10 min.','Mélanger et servir.'],note:'Bolognaise végétale du week-end. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine framboises skyr famille',kcal:410,p:22,g:58,l:13,portions:'4 pers.',ings:['Flocons avoine mixés 30g','Oeufs 1 pièce','Lait végétal 30ml','Skyr 30g','Framboises 50g','Beurre cacahuète 5g','Miel 4g'],steps:['Mixer flocons + oeufs + lait en pâte lisse.','Cuire des pancakes 3 min/face.','Servir avec skyr, framboises, miel et beurre de cacahuète.'],note:''},
    {moment:'Déjeuner',nom:'Cuisses poulet rôties légumes du four patate douce',kcal:540,p:45,g:46,l:20,portions:'4 pers.',ings:['Cuisses poulet désossées 130g','Patate douce 130g','Courgette 60g','Poivron rouge 60g','Oignon','Ail','Huile olive 5g','Herbes de Provence'],steps:['Préchauffer le four à 200°C.','Couper les légumes, disposer avec huile + herbes.','Déposer les cuisses de poulet par-dessus.','Rôtir 30 min en retournant à mi-cuisson.','Servir depuis le plat.'],note:'Plat du week-end (35 min).'},
    {moment:'Collation',nom:'Skyr amandes beurre cacahuète',kcal:204,p:14,g:9,l:13,portions:'2 adultes',ings:['Skyr 100g','Amandes 15g','Beurre cacahuète 10g'],steps:['Mélanger skyr + beurre cacahuète, parsemer amandes.'],note:''},
    {moment:'Dîner',nom:'Bolognaise pois chiches carottes pâtes complètes',kcal:440,p:20,g:60,l:12,portions:'4 pers.',ings:['Pois chiches en bocal 70g','Carottes 40g','Tomates concassées 80g','Oignon','Ail','Pâtes complètes 70g','Huile olive 3g','Herbes de Provence'],steps:['Faire revenir oignon + ail + carottes 5 min.','Ajouter pois chiches + tomates concassées + eau + herbes.','Mijoter 15 min.','Cuire les pâtes complètes.','Mélanger et servir.'],note:'Bolognaise végétale du week-end.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr framboises banane amandes famille',kcal:340,p:18,g:46,l:9,portions:'4 pers.',ings:['Skyr 100g','Yaourt fruits mixé 60g','Flocons avoine 25g','Framboises 50g','Banane 40g','Amandes 10g'],steps:['Répartir le skyr et le yaourt en bols.','Trancher la banane.','Disposer les framboises.','Parsemer flocons et amandes.'],note:''},
    {moment:'Déjeuner',nom:'Rôti de boeuf maigre carottes pommes de terre',kcal:480,p:40,g:36,l:20,portions:'4 pers.',ings:['Rôti de boeuf maigre 110g','Pommes de terre 100g','Carottes 60g','Oignon','Ail','Huile olive 4g','Thym romarin'],steps:['Préchauffer le four à 200°C.','Couper les légumes, disposer dans un plat avec huile + thym.','Saisir le rôti 3 min/face à la poêle.','Déposer le rôti sur les légumes, rôtir 35 min en arrosant.','Laisser reposer 10 min avant de trancher.'],note:'Plat dominical (45 min). Portion réduite pour les enfants.'},
    {moment:'Collation',nom:'Porridge beurre cacahuète famille',kcal:230,p:10,g:28,l:10,portions:'4 pers.',ings:['Flocons avoine 40g','Lait végétal 80ml','Beurre cacahuète 10g'],steps:['Cuire les flocons avec le lait végétal 4 min.','Incorporer le beurre de cacahuète.','Servir tiède.'],note:''},
    {moment:'Dîner',nom:'Soupe potiron lentilles corail curry',kcal:310,p:14,g:44,l:8,portions:'4 pers.',ings:['Potiron 150g','Lentilles corail 45g','Lait de coco 25ml','Oignon','Curry doux','Bouillon légumes 200ml','Huile olive 2g'],steps:['Faire revenir oignon + curry dans l\'huile 2 min.','Ajouter potiron en dés + lentilles corail + bouillon.','Cuire 15 min à feu moyen.','Mixer avec le lait de coco.','Assaisonner et servir chaud.'],note:'Soupe douce du dimanche soir. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr framboises banane amandes famille',kcal:400,p:23,g:54,l:11,portions:'4 pers.',ings:['Skyr 100g','Yaourt fruits mixé 80g','Flocons avoine 35g','Framboises 50g','Banane 50g','Amandes 15g','Miel 4g'],steps:['Répartir le skyr et le yaourt en bols.','Trancher la banane.','Disposer les framboises.','Parsemer flocons, amandes et filet de miel.'],note:''},
    {moment:'Déjeuner',nom:'Rôti de boeuf maigre carottes pommes de terre',kcal:540,p:48,g:42,l:22,portions:'4 pers.',ings:['Rôti de boeuf maigre 130g','Pommes de terre 120g','Carottes 60g','Oignon','Ail','Huile olive 5g','Thym romarin'],steps:['Préchauffer le four à 200°C.','Couper les légumes, disposer avec huile + thym.','Saisir le rôti 3 min/face.','Rôtir 35 min en arrosant.','Laisser reposer 10 min.'],note:'Plat dominical (45 min).'},
    {moment:'Collation',nom:'Porridge beurre cacahuète',kcal:258,p:11,g:32,l:12,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 100ml','Beurre cacahuète 14g'],steps:['Cuire les flocons avec le lait végétal 4 min.','Incorporer le beurre de cacahuète.','Servir tiède.'],note:''},
    {moment:'Dîner',nom:'Soupe potiron lentilles corail curry',kcal:310,p:14,g:44,l:8,portions:'4 pers.',ings:['Potiron 150g','Lentilles corail 45g','Lait de coco 25ml','Oignon','Curry doux','Bouillon légumes 200ml','Huile olive 2g'],steps:['Faire revenir oignon + curry 2 min.','Ajouter potiron + lentilles + bouillon.','Cuire 15 min.','Mixer avec le lait de coco.','Assaisonner et servir.'],note:'Soupe douce du dimanche soir.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
];

const semaine2=[
  {f:[
    {moment:'Petit-déjeuner',nom:'Smoothie bowl skyr mangue graines de chia',kcal:340,p:20,g:42,l:9,portions:'2 adultes',ings:['Skyr 130g','Mangue 80g','Flocons avoine 40g','Graines de chia 8g','Cannelle'],steps:['Verser le skyr dans un bol.','Disposer la mangue coupée en dés.','Parsemer flocons et graines de chia.','Saupoudrer de cannelle et déguster frais.'],note:''},
    {moment:'Déjeuner',nom:'Cabillaud poêlé patate douce épinards',kcal:355,p:25,g:38,l:10,portions:'2 adultes',ings:['Filet cabillaud 120g','Patate douce 120g','Épinards frais 80g','Ail','Huile olive 5g','Citron herbes'],steps:['Cuire la patate douce vapeur 12 min.','Poêler le cabillaud 4 min/face avec ail.','Faire sauter les épinards 3 min.','Servir avec citron pressé et herbes fraîches.'],note:'Poisson gras riche en oméga-3.'},
    {moment:'Collation',nom:'Petit suisse miel amandes',kcal:170,p:10,g:14,l:8,portions:'2 adultes',ings:['Petit suisse 100g','Miel 8g','Amandes 8g'],steps:['Verser le miel sur le petit suisse.','Parsemer les amandes.'],note:''},
    {moment:'Dîner',nom:'Velouté patate douce lentilles corail coco',kcal:370,p:14,g:54,l:8,portions:'4 pers.',ings:['Lentilles corail 50g','Patate douce 100g','Carottes 50g','Lait de coco 25ml','Oignon','Ail','Curry doux','Huile olive 2g','Persil'],steps:['Faire revenir oignon + ail + curry dans l\'huile 2 min.','Ajouter patate douce + carottes en dés + lentilles corail + 250ml d\'eau.','Cuire 15 min à feu moyen.','Mixer avec le lait de coco.','Parsemer de persil et servir.'],note:'Soupe veloutée 18 min. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Smoothie bowl skyr mangue graines de chia',kcal:400,p:25,g:52,l:11,portions:'2 adultes',ings:['Skyr 150g','Mangue 100g','Flocons avoine 55g','Graines de chia 10g','Cannelle'],steps:['Verser le skyr dans un bol.','Disposer la mangue coupée en dés.','Parsemer flocons et graines de chia.','Saupoudrer de cannelle et déguster.'],note:''},
    {moment:'Déjeuner',nom:'Cabillaud poêlé patate douce épinards',kcal:415,p:32,g:44,l:11,portions:'2 adultes',ings:['Filet cabillaud 140g','Patate douce 130g','Épinards frais 80g','Ail','Huile olive 6g','Citron herbes'],steps:['Cuire la patate douce vapeur 12 min.','Poêler le cabillaud 4 min/face avec ail.','Faire sauter les épinards 3 min.','Servir avec citron et herbes.'],note:'Poisson gras riche en oméga-3.'},
    {moment:'Collation',nom:'Petit suisse miel amandes',kcal:215,p:13,g:16,l:11,portions:'2 adultes',ings:['Petit suisse 150g','Miel 10g','Amandes 12g'],steps:['Verser le miel sur le petit suisse.','Parsemer les amandes.'],note:''},
    {moment:'Dîner',nom:'Velouté patate douce lentilles corail coco',kcal:370,p:14,g:54,l:8,portions:'4 pers.',ings:['Lentilles corail 50g','Patate douce 100g','Carottes 50g','Lait de coco 25ml','Oignon','Ail','Curry doux','Huile olive 2g','Persil'],steps:['Faire revenir oignon + ail + curry 2 min.','Ajouter patate douce + carottes + lentilles + eau.','Cuire 15 min.','Mixer avec lait de coco.','Parsemer de persil.'],note:'Soupe veloutée 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Skyr myrtilles flocons amandes',kcal:340,p:20,g:42,l:10,portions:'2 adultes',ings:['Skyr 130g','Myrtilles surgelées 50g','Flocons avoine 45g','Amandes 8g','Cannelle'],steps:['Décongeler légèrement les myrtilles.','Verser le skyr dans un bol.','Parsemer flocons et amandes.','Disposer les myrtilles et la cannelle.'],note:''},
    {moment:'Déjeuner',nom:'Poulet curry coco riz basmati courgettes',kcal:450,p:32,g:46,l:14,portions:'2 adultes',ings:['Blanc poulet 100g','Riz basmati 65g','Courgette 100g','Lait de coco 25ml','Oignon','Curry doux','Huile olive 3g'],steps:['Cuire le riz basmati 12 min.','Faire revenir oignon + curry dans l\'huile 2 min.','Ajouter le poulet en dés, dorer 5 min.','Ajouter courgette + lait de coco, mijoter 6 min.','Servir avec le riz.'],note:''},
    {moment:'Collation',nom:'Yaourt fruits mixé noix',kcal:175,p:7,g:18,l:9,portions:'2 adultes',ings:['Yaourt fruits mixé 130g','Noix 12g'],steps:['Déguster ensemble.'],note:''},
    {moment:'Dîner',nom:'Tortilla espagnole oeufs pommes de terre poivrons',kcal:330,p:18,g:26,l:16,portions:'4 pers.',ings:['Oeufs 2 pièces','Pommes de terre 100g','Poivron rouge 50g','Oignon','Huile olive 4g','Persil'],steps:['Cuire les pommes de terre en dés vapeur 10 min.','Faire revenir oignon + poivron + pommes de terre 5 min.','Battre les oeufs et verser sur les légumes.','Cuire à feu doux 6 min, finir sous le gril 2 min.','Parsemer de persil frais.'],note:'Tortilla familiale 18 min. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:148,p:4,g:9,l:11,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Skyr myrtilles flocons amandes',kcal:395,p:24,g:50,l:13,portions:'2 adultes',ings:['Skyr 150g','Myrtilles surgelées 60g','Flocons avoine 60g','Amandes 10g','Cannelle'],steps:['Décongeler légèrement les myrtilles.','Verser le skyr dans un bol.','Parsemer flocons et amandes.','Disposer myrtilles et cannelle.'],note:''},
    {moment:'Déjeuner',nom:'Poulet curry coco riz basmati courgettes',kcal:510,p:39,g:54,l:16,portions:'2 adultes',ings:['Blanc poulet 120g','Riz basmati 80g','Courgette 100g','Lait de coco 30ml','Oignon','Curry doux','Huile olive 4g'],steps:['Cuire le riz basmati 12 min.','Faire revenir oignon + curry 2 min.','Ajouter le poulet, dorer 5 min.','Ajouter courgette + lait de coco, mijoter 6 min.','Servir.'],note:''},
    {moment:'Collation',nom:'Skyr beurre cacahuète',kcal:200,p:15,g:10,l:11,portions:'2 adultes',ings:['Skyr 170g','Beurre cacahuète 13g'],steps:['Mélanger.'],note:''},
    {moment:'Dîner',nom:'Tortilla espagnole oeufs pommes de terre poivrons',kcal:380,p:22,g:28,l:20,portions:'4 pers.',ings:['Oeufs 3 pièces','Pommes de terre 100g','Poivron rouge 50g','Oignon','Huile olive 4g','Persil'],steps:['Cuire les pommes de terre en dés vapeur 10 min.','Faire revenir oignon + poivron + pommes de terre 5 min.','Battre les oeufs et verser.','Cuire 6 min, finir sous le gril 2 min.','Parsemer de persil.'],note:'Tortilla familiale 18 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:148,p:4,g:9,l:11,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Porridge pomme cannelle amandes',kcal:345,p:13,g:50,l:10,portions:'2 adultes',ings:['Flocons avoine 55g','Lait végétal 100ml','Pomme 80g','Amandes 12g','Cannelle'],steps:['Cuire les flocons avec le lait végétal 4 min en remuant.','Râper la pomme et l\'incorporer.','Parsemer amandes et cannelle.','Servir chaud.'],note:''},
    {moment:'Déjeuner',nom:'Sardines à l\'huile riz complet tomates cerises avocat',kcal:445,p:28,g:42,l:16,portions:'2 adultes',ings:['Sardines à l\'huile 80g','Riz complet 60g','Tomates cerises 80g','Avocat 30g','Oignon rouge','Huile olive 3g','Citron herbes'],steps:['Cuire le riz complet 18 min.','Égoutter les sardines.','Couper l\'avocat et les tomates cerises en deux.','Assembler riz + sardines + tomates cerises + avocat + oignon rouge.','Assaisonner citron + huile + herbes.'],note:'Poisson riche en oméga-3.'},
    {moment:'Collation',nom:'Skyr beurre cacahuète',kcal:177,p:13,g:9,l:9,portions:'2 adultes',ings:['Skyr 150g','Beurre cacahuète 12g'],steps:['Mélanger ou déguster séparément.'],note:''},
    {moment:'Dîner',nom:'Chili pois chiches haricots rouges riz complet',kcal:420,p:18,g:60,l:8,portions:'4 pers.',ings:['Pois chiches en bocal 50g','Haricots rouges en bocal 70g','Riz complet 50g','Tomates concassées 80g','Poivron 50g','Oignon','Ail','Cumin paprika','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Faire revenir oignon + ail + poivron + épices 5 min.','Ajouter pois chiches + haricots rouges + tomates concassées + 60ml d\'eau.','Mijoter 10 min à feu moyen.','Servir sur le riz complet.'],note:'Chili doux pour les enfants. Végétarien. 25 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Porridge pomme cannelle amandes',kcal:395,p:15,g:58,l:12,portions:'2 adultes',ings:['Flocons avoine 70g','Lait végétal 120ml','Pomme 100g','Amandes 15g','Cannelle'],steps:['Cuire les flocons avec le lait végétal 4 min.','Râper la pomme et l\'incorporer.','Parsemer amandes et cannelle.','Servir chaud.'],note:''},
    {moment:'Déjeuner',nom:'Sardines à l\'huile riz complet tomates cerises avocat',kcal:510,p:34,g:48,l:18,portions:'2 adultes',ings:['Sardines à l\'huile 100g','Riz complet 80g','Tomates cerises 80g','Avocat 40g','Oignon rouge','Huile olive 4g','Citron herbes'],steps:['Cuire le riz complet 18 min.','Égoutter les sardines.','Couper avocat et tomates cerises.','Assembler et assaisonner.'],note:'Poisson riche en oméga-3.'},
    {moment:'Collation',nom:'Skyr amandes',kcal:200,p:16,g:10,l:11,portions:'2 adultes',ings:['Skyr 170g','Amandes 18g'],steps:['Déguster.'],note:''},
    {moment:'Dîner',nom:'Chili pois chiches haricots rouges riz complet',kcal:420,p:18,g:60,l:8,portions:'4 pers.',ings:['Pois chiches en bocal 50g','Haricots rouges en bocal 70g','Riz complet 50g','Tomates concassées 80g','Poivron 50g','Oignon','Ail','Cumin paprika','Huile olive 3g'],steps:['Cuire le riz complet 20 min.','Faire revenir oignon + ail + poivron + épices 5 min.','Ajouter haricots + tomates + eau.','Mijoter 10 min.','Servir sur le riz.'],note:'Chili doux. Végétarien. 25 min.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Oeufs durs pain complet avocat tomates',kcal:340,p:18,g:30,l:14,portions:'2 adultes',ings:['Oeufs 2 pièces','Pain complet 40g','Avocat 40g','Tomates 80g','Herbes ciboulette'],steps:['Cuire les oeufs 9 min, écaler.','Toaster le pain complet.','Écraser l\'avocat sur le pain.','Trancher les oeufs et les tomates, dresser avec ciboulette.'],note:''},
    {moment:'Déjeuner',nom:'Boeuf haché poêlée poivrons pâtes complètes',kcal:440,p:33,g:46,l:13,portions:'2 adultes',ings:['Boeuf haché maigre 90g','Pâtes complètes 65g','Poivron rouge 100g','Oignon','Ail','Huile olive 4g','Herbes de Provence'],steps:['Cuire les pâtes complètes 8-10 min.','Faire revenir oignon + ail dans l\'huile 2 min.','Ajouter le poivron en lamelles, cuire 5 min.','Ajouter le boeuf haché, dorer 6 min en remuant.','Mélanger aux pâtes, assaisonner herbes.'],note:''},
    {moment:'Collation',nom:'Skyr amandes',kcal:175,p:13,g:9,l:10,portions:'2 adultes',ings:['Skyr 150g','Amandes 15g'],steps:['Déguster ensemble.'],note:''},
    {moment:'Dîner',nom:'Soupe lentilles vertes poireaux carottes',kcal:370,p:18,g:54,l:7,portions:'4 pers.',ings:['Lentilles vertes en bocal 80g','Poireaux 80g','Carottes 60g','Oignon','Ail','Bouillon légumes 300ml','Thym herbes laurier','Huile olive 2g','Persil'],steps:['Faire revenir oignon + ail + poireaux émincés dans l\'huile 4 min.','Ajouter carottes en rondelles + lentilles vertes + bouillon + thym laurier.','Cuire 15 min à feu moyen.','Rectifier l\'assaisonnement.','Parsemer de persil frais.'],note:'Soupe consistante 20 min. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:148,p:4,g:9,l:11,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster ensemble.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Oeufs durs pain complet avocat tomates',kcal:395,p:22,g:36,l:16,portions:'2 adultes',ings:['Oeufs 3 pièces','Pain complet 50g','Avocat 50g','Tomates 100g','Herbes ciboulette'],steps:['Cuire les oeufs 9 min, écaler.','Toaster le pain complet.','Écraser l\'avocat sur le pain.','Trancher les oeufs et les tomates, dresser avec ciboulette.'],note:''},
    {moment:'Déjeuner',nom:'Boeuf haché poêlée poivrons pâtes complètes',kcal:505,p:40,g:52,l:15,portions:'2 adultes',ings:['Boeuf haché maigre 110g','Pâtes complètes 80g','Poivron rouge 100g','Oignon','Ail','Huile olive 5g','Herbes de Provence'],steps:['Cuire les pâtes complètes 8-10 min.','Faire revenir oignon + ail 2 min.','Ajouter poivron, cuire 5 min.','Ajouter boeuf haché, dorer 6 min.','Mélanger aux pâtes et assaisonner.'],note:''},
    {moment:'Collation',nom:'Skyr beurre cacahuète',kcal:200,p:15,g:10,l:11,portions:'2 adultes',ings:['Skyr 170g','Beurre cacahuète 13g'],steps:['Mélanger.'],note:''},
    {moment:'Dîner',nom:'Soupe lentilles vertes poireaux carottes',kcal:370,p:18,g:54,l:7,portions:'4 pers.',ings:['Lentilles vertes en bocal 80g','Poireaux 80g','Carottes 60g','Oignon','Ail','Bouillon légumes 300ml','Thym herbes laurier','Huile olive 2g','Persil'],steps:['Faire revenir oignon + ail + poireaux 4 min.','Ajouter carottes + lentilles + bouillon + aromates.','Cuire 15 min.','Rectifier l\'assaisonnement.','Parsemer de persil.'],note:'Soupe consistante 20 min.'},
    {moment:'Collation soir',nom:'Chocolat noir amandes',kcal:148,p:4,g:9,l:11,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g','Amandes 8g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature granola fruits rouges',kcal:320,p:12,g:42,l:10,portions:'2 adultes',ings:['Yaourt nature 150g','Flocons avoine 35g','Fruits rouges 50g','Amandes 8g','Miel 5g'],steps:['Verser le yaourt nature dans un bol.','Ajouter les fruits rouges décongelés.','Parsemer flocons et amandes.','Filer un trait de miel.'],note:''},
    {moment:'Déjeuner',nom:'Poulet sauce yaourt riz basmati brocolis',kcal:440,p:33,g:46,l:11,portions:'2 adultes',ings:['Blanc poulet 100g','Riz basmati 65g','Brocolis 100g','Yaourt nature 30g','Ail','Curry doux','Huile olive 3g','Citron herbes'],steps:['Cuire le riz basmati 12 min.','Cuire les brocolis vapeur 6 min.','Poêler le poulet en lanières 7 min.','Mélanger yaourt + ail + curry + citron pour la sauce.','Servir riz + poulet + brocolis nappé de sauce yaourt.'],note:''},
    {moment:'Collation',nom:'Petit suisse beurre cacahuète',kcal:171,p:7,g:10,l:11,portions:'2 adultes',ings:['Petit suisse 60g','Beurre cacahuète 15g'],steps:['Déguster ensemble.'],note:''},
    {moment:'Dîner',nom:'Bowl pois chiches rôtis patate douce tahini',kcal:400,p:18,g:48,l:14,portions:'4 pers.',ings:['Pois chiches en bocal 70g','Patate douce 90g','Courgette 80g','Tomates cerises 60g','Ail','Huile olive 5g','Cumin','Persil'],steps:['Préchauffer le four à 200°C.','Couper patate douce + courgette en dés, arroser huile + cumin.','Rôtir 15 min avec les pois chiches égouttés.','Ajouter tomates cerises 3 min en fin de cuisson.','Servir avec ail + citron + huile olive.'],note:'Bowl complet 20 min. Végétarien. Les enfants adorent.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Yaourt nature granola fruits rouges',kcal:370,p:15,g:50,l:12,portions:'2 adultes',ings:['Yaourt nature 180g','Flocons avoine 50g','Fruits rouges 60g','Amandes 10g','Miel 6g'],steps:['Verser le yaourt nature dans un bol.','Ajouter les fruits rouges.','Parsemer flocons et amandes.','Filer un trait de miel.'],note:''},
    {moment:'Déjeuner',nom:'Poulet sauce yaourt riz basmati brocolis',kcal:500,p:40,g:54,l:13,portions:'2 adultes',ings:['Blanc poulet 120g','Riz basmati 80g','Brocolis 100g','Yaourt nature 40g','Ail','Curry doux','Huile olive 4g','Citron herbes'],steps:['Cuire le riz basmati 12 min.','Cuire les brocolis vapeur 6 min.','Poêler le poulet 7 min.','Mélanger yaourt + ail + curry + citron.','Servir nappé de sauce.'],note:''},
    {moment:'Collation',nom:'Skyr beurre cacahuète',kcal:177,p:13,g:9,l:9,portions:'2 adultes',ings:['Skyr 150g','Beurre cacahuète 12g'],steps:['Mélanger.'],note:''},
    {moment:'Dîner',nom:'Bowl pois chiches rôtis patate douce tahini',kcal:400,p:18,g:48,l:14,portions:'4 pers.',ings:['Pois chiches en bocal 70g','Patate douce 90g','Courgette 80g','Tomates cerises 60g','Ail','Huile olive 5g','Cumin','Persil'],steps:['Préchauffer le four à 200°C.','Couper patate douce + courgette en dés, arroser huile + cumin.','Rôtir 15 min avec les pois chiches.','Ajouter tomates cerises 3 min en fin.','Servir avec ail + citron + huile olive.'],note:'Bowl complet 20 min. Végétarien.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine banane chocolat famille',kcal:355,p:16,g:52,l:11,portions:'4 pers.',ings:['Flocons avoine mixés 30g','Oeufs 1 pièce','Lait végétal 30ml','Banane 60g','Pépites chocolat noir 6g','Skyr 30g'],steps:['Mixer flocons + oeufs + lait + banane en pâte lisse.','Incorporer les pépites de chocolat noir.','Cuire des pancakes 3 min/face à feu moyen.','Servir avec une cuillère de skyr.'],note:'Les enfants adorent !'},
    {moment:'Déjeuner',nom:'Tajine poulet pois chiches abricots semoule',kcal:455,p:33,g:52,l:13,portions:'4 pers.',ings:['Cuisses poulet désossées 100g','Pois chiches en bocal 60g','Semoule complète 55g','Abricots secs 10g','Carottes 60g','Oignon','Ail','Ras el hanout curry','Coriandre','Huile olive 4g'],steps:['Faire revenir oignon + ail + épices dans l\'huile 2 min.','Ajouter le poulet et dorer 5 min.','Ajouter carottes en rondelles + abricots + 250ml d\'eau, mijoter 25 min.','Incorporer les pois chiches 5 min avant la fin.','Préparer la semoule complète selon le paquet.','Servir avec coriandre fraîche.'],note:'Plat du week-end (35 min). Parfumé, les enfants adorent.'},
    {moment:'Collation',nom:'Yaourt fruits mixé amandes famille',kcal:138,p:5,g:18,l:5,portions:'4 pers.',ings:['Yaourt fruits mixé 60g','Amandes 6g'],steps:['Répartir en bols avec amandes.'],note:''},
    {moment:'Dîner',nom:'Curry indien lentilles patate douce coco',kcal:425,p:18,g:60,l:12,portions:'4 pers.',ings:['Lentilles corail 55g','Patate douce 100g','Tomates concassées 80g','Lait de coco 35ml','Oignon','Ail gingembre','Garam masala curry','Coriandre','Huile olive 3g'],steps:['Faire revenir oignon + ail + gingembre + épices dans l\'huile 3 min.','Ajouter patate douce en dés + lentilles corail + 250ml d\'eau.','Cuire 15 min à feu moyen.','Ajouter tomates concassées + lait de coco, mijoter 5 min.','Parsemer de coriandre fraîche et servir.'],note:'Plat indien du week-end (25 min). Végétarien.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Pancakes avoine banane chocolat famille',kcal:410,p:20,g:60,l:13,portions:'4 pers.',ings:['Flocons avoine mixés 30g','Oeufs 1 pièce','Lait végétal 30ml','Banane 50g','Pépites chocolat noir 8g','Skyr 30g','Beurre cacahuète 5g'],steps:['Mixer flocons + oeufs + lait + banane.','Incorporer les pépites de chocolat noir.','Cuire des pancakes 3 min/face.','Servir avec skyr et beurre de cacahuète.'],note:''},
    {moment:'Déjeuner',nom:'Tajine poulet pois chiches abricots semoule',kcal:515,p:40,g:58,l:15,portions:'4 pers.',ings:['Cuisses poulet désossées 120g','Pois chiches en bocal 70g','Semoule complète 70g','Abricots secs 10g','Carottes 60g','Oignon','Ail','Ras el hanout curry','Coriandre','Huile olive 5g'],steps:['Faire revenir oignon + ail + épices 2 min.','Ajouter le poulet, dorer 5 min.','Ajouter carottes + abricots + eau, mijoter 25 min.','Incorporer pois chiches 5 min avant la fin.','Préparer la semoule complète.','Servir avec coriandre.'],note:'Plat du week-end (35 min).'},
    {moment:'Collation',nom:'Skyr amandes beurre cacahuète',kcal:204,p:14,g:9,l:13,portions:'2 adultes',ings:['Skyr 100g','Amandes 15g','Beurre cacahuète 10g'],steps:['Mélanger skyr + beurre cacahuète, parsemer amandes.'],note:''},
    {moment:'Dîner',nom:'Curry indien lentilles patate douce coco',kcal:425,p:18,g:60,l:12,portions:'4 pers.',ings:['Lentilles corail 55g','Patate douce 100g','Tomates concassées 80g','Lait de coco 35ml','Oignon','Ail gingembre','Garam masala curry','Coriandre','Huile olive 3g'],steps:['Faire revenir oignon + ail + gingembre + épices 3 min.','Ajouter patate douce + lentilles + eau.','Cuire 15 min.','Ajouter tomates + lait de coco, mijoter 5 min.','Parsemer de coriandre.'],note:'Plat indien du week-end (25 min). Végétarien.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
  {f:[
    {moment:'Petit-déjeuner',nom:'Bol skyr granola pêche noisettes famille',kcal:340,p:18,g:44,l:10,portions:'4 pers.',ings:['Skyr 100g','Yaourt fruits mixé 80g','Flocons avoine 30g','Pêche 60g','Noisettes 10g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la pêche en quartiers.','Parsemer flocons et noisettes.'],note:''},
    {moment:'Déjeuner',nom:'Boeuf bourguignon léger carottes pommes de terre',kcal:440,p:30,g:38,l:17,portions:'4 pers.',ings:['Boeuf maigre 80g','Pommes de terre 120g','Carottes 80g','Champignons 50g','Oignon','Ail','Vinaigre balsamique 15ml','Bouillon légumes 100ml','Huile olive 4g','Thym laurier'],steps:['Saisir le boeuf en cubes 5 min dans l\'huile.','Ajouter oignon + ail + carottes + champignons, cuire 5 min.','Déglacer au vinaigre balsamique.','Ajouter pommes de terre + bouillon + thym laurier.','Mijoter 30 min à feu doux à couvert.','Rectifier l\'assaisonnement.'],note:'Plat dominical familial (45 min).'},
    {moment:'Collation',nom:'Porridge beurre cacahuète famille',kcal:230,p:10,g:28,l:10,portions:'4 pers.',ings:['Flocons avoine 40g','Lait végétal 80ml','Beurre cacahuète 10g'],steps:['Cuire les flocons avec le lait végétal 4 min.','Incorporer le beurre de cacahuète.','Servir tiède.'],note:''},
    {moment:'Dîner',nom:'Soupe ratatouille pâtes complètes basilic',kcal:330,p:13,g:50,l:7,portions:'4 pers.',ings:['Aubergine 80g','Courgette 80g','Tomates concassées 100g','Pâtes complètes 35g','Poivron 50g','Oignon','Ail','Bouillon légumes 200ml','Basilic','Huile olive 3g'],steps:['Faire revenir oignon + ail + aubergine en dés 5 min.','Ajouter courgette + poivron en dés, cuire 5 min.','Ajouter tomates concassées + bouillon, mijoter 10 min.','Incorporer les pâtes complètes, cuire 8 min.','Parsemer de basilic frais et servir.'],note:'Soupe-repas du dimanche soir. Légère et complète.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster en fin de soirée.'],note:'Adultes uniquement.'},
  ],m:[
    {moment:'Petit-déjeuner',nom:'Bol skyr granola pêche noisettes famille',kcal:395,p:22,g:50,l:12,portions:'4 pers.',ings:['Skyr 100g','Yaourt fruits mixé 80g','Flocons avoine 35g','Pêche 80g','Noisettes 12g','Miel 5g'],steps:['Répartir le skyr et le yaourt en bols.','Couper la pêche.','Parsemer flocons, noisettes et filet de miel.'],note:''},
    {moment:'Déjeuner',nom:'Boeuf bourguignon léger carottes pommes de terre',kcal:490,p:36,g:42,l:21,portions:'4 pers.',ings:['Boeuf maigre 100g','Pommes de terre 130g','Carottes 80g','Champignons 50g','Oignon','Ail','Vinaigre balsamique 15ml','Bouillon légumes 120ml','Huile olive 5g','Thym laurier'],steps:['Saisir le boeuf 5 min.','Ajouter oignon + ail + carottes + champignons, cuire 5 min.','Déglacer au vinaigre balsamique.','Ajouter pommes de terre + bouillon + aromates.','Mijoter 30 min à couvert.','Rectifier l\'assaisonnement.'],note:'Plat dominical familial (45 min).'},
    {moment:'Collation',nom:'Porridge beurre cacahuète',kcal:258,p:11,g:32,l:12,portions:'2 adultes',ings:['Flocons avoine 50g','Lait végétal 100ml','Beurre cacahuète 14g'],steps:['Cuire les flocons avec le lait végétal 4 min.','Incorporer le beurre de cacahuète.','Servir tiède.'],note:''},
    {moment:'Dîner',nom:'Soupe ratatouille pâtes complètes basilic',kcal:330,p:13,g:50,l:7,portions:'4 pers.',ings:['Aubergine 80g','Courgette 80g','Tomates concassées 100g','Pâtes complètes 35g','Poivron 50g','Oignon','Ail','Bouillon légumes 200ml','Basilic','Huile olive 3g'],steps:['Faire revenir oignon + ail + aubergine 5 min.','Ajouter courgette + poivron, cuire 5 min.','Ajouter tomates + bouillon, mijoter 10 min.','Incorporer les pâtes, cuire 8 min.','Parsemer basilic frais.'],note:'Soupe-repas du dimanche soir.'},
    {moment:'Collation soir',nom:'Chocolat noir 70%',kcal:90,p:1,g:8,l:6,portions:'2 adultes',ings:['Chocolat noir 70%+ 15g'],steps:['Déguster.'],note:'Adultes uniquement.'},
  ]},
];

const semaines=[semaine1, semaine2];
const semaineLabels=['Semaine en cours','Semaine suivante'];

